--- 
  - name: Get all joined systems
    delegate_to: localhost
    run_once: true
    command: > 
      scripts/ol_manager/ol_manager.py
      'admin' 
      '5PyaCj2*I4@9' 
      'https://oracle-linux-manager01.kcloud.local/rpc/api' 
      -l
    register: registered_systems

      